### ISSUE TITLE
Circular reference on save

### ISSUE THREAD

**Issue by xxv** [SwartzCr/nekoatsume#17]
```
python display.py
[Welcome!] Your yard currently has a medium condo in it, occupied by no one
[Welcome!] Your yard currently has a bowl of dry food in it with 276 time remaining
[Welcome!] You have a bowl of dry food in your yard with 276 minutes of food remaining
[Main Menu] Your options are: shop, quit, yard, look, collect money, check food, help
[Main Menu] Choose an action! quit
[Goodbye!] Saving game! See you later!
Traceback (most recent call last):
  File "display.py", line 125, in <module>
    main()
  File "display.py", line 120, in main
    actions[inp](data)
  File "display.py", line 92, in quit
    prep_data_on_close(data)
  File "display.py", line 30, in prep_data_on_close
    store_data(data)
  File "display.py", line 20, in store_data
    json.dump(data, f)
  File "/usr/lib/python2.7/json/__init__.py", line 189, in dump
    for chunk in iterable:
  File "/usr/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 348, in _iterencode_dict
    raise ValueError("Circular reference detected")
ValueError: Circular reference detected
```

Unfortunately, I wasn't able to dig into it before my data file got trounced.

**Comment by brianshumate** [comment]
I have also seen this a couple times too, and wonder if we're somehow serializing an exception or something similar with `json.dump`.

I have not managed to catch it happening again lately, though.

**Comment by xxv** [comment]
Alright, so I just got it again and here's my corrupted data.json file:

``` json
{"yard": [{"description": "A medium sized kitty condo with full carpeting and room for up to 5 cats!", "in_yard": true, "currency": "s", "cost": 150, "occupant": {"name": "Pukka", "in_yard": true, "treasure": "It's a block of surf wax", "given_treasure": false, "on_toy": 
```

**Comment by brianshumate** [comment]
The main issue here is that JSON itself has no ability to handle the circular references which are being introduced by some of the dictionaries in our game data. This is an age old problem encountered when doing object serialization with JSON.

There are different approaches to handling this available to us:
1. Remove the circular references (where are they and why?)
2. Use a different data format — YAML for instance can handle circular
   references; this option might not be ideal for us, however
3. Use some kind of workaround in order to avoid using third-party modules;
   one such workaround is [dump.py](https://gist.github.com/patkujawa-wf/ae978919f4c68c9c8de8) which stems from this 
   [Stack Overflow discussion](https://stackoverflow.com/questions/27830888/work-around-pythons-json-module-not-liking-circular-references) — this is
   not an elegant solution and could be problematic in the future
4. Use a third party module like [jsonpickle](https://jsonpickle.github.io/);
   if we are not opposed to third party modules, then this is could be a good solution.
5. Use a more heavy duty third party module like 
   [marshmallow](https://marshmallow.readthedocs.org/en/latest/quickstart.html)
   for object serialization; this could be awesome or overkill, as it would
   require us to model the game data and use those models in our code

It depends on how far we want to take this, and what we would want to ask of people who want to play the game. Obviously, keeping it simple means it is easier for folks to grab and play the game, but this implies that we need to use some kind of workaround.

On the other hand, if we want to introduce a third party module, then we'll need more detailed documentation and it will require a bit more work for the player to get an play the game (think setting up virtualenv or using pipsi, or polluting the system Python with our chosen module dependency). However, choosing a more robust serialization approach could make the game far more awesome down the road. It is worth noting that it seems also that options 3 and 4 would require the code to be more object oriented, however.

Personally, I think that the introduction of third party modules is fine, and that if a player is going to try a game written in Python, then the act of setting up a virtualenv or using pipsi to prepare the game environment is a good Python learning experience even for the most novice of Python folks out there.

I don't see it as a hindrance per se, but we'd also need to give those who want to play the game a chance to provide feedback as to how much effort they are comfortable with in obtaining and setting up the game prior to enjoying
it.

There are some trade-offs here, and so we need to make a careful decision about how we want to go forward.

That's my overly stretched €0.018. :smile:

**Comment by xxv** [comment]
Why not just get rid of the circular references?

**Comment by SwartzCr** [comment]
I'm with @xxv on this
while I'm okay with getting to the point where we need people to install a virtualenv or other third party dependencies - I know that things like pickle can be scary and would rather not have people rely on them if we can find a simpler answer. I'm happy to do some testing over the weekend to see if I can re-pro

**Comment by brianshumate** [comment]
:+1: Yeah, I think the circular refs are being introduced most likely in dictionary usage. I've never dealt with something like this though so it'd be a good learning experience to understand how they came to be and how to remove them.

**Comment by brianshumate** [comment]
Saw [this disucssion](https://twitter.com/swartzcr/status/697660296899334144) on Twitter.

Unfortunately, I don't think this is the cause as I just hit the error with Python 3.5.1 :disappointed:

**Comment by brianshumate** [comment]
Okay, per the great suggestion of _encthenet_ on Twitter, I tried adding `allow_nan=False` to the `json.dump` call, but I still hit the error, and it looks like I can now reliably reproduce it with these steps:
1. Start game with an empty database
2. shop → buy → bowl of dry food
3. buy → sparkle ball
4. leave shop
5. yard
6. place food → bowl of dry food
7. place toy → sparkle ball
8. leave yard
9. quit
10. Start game
11. quit

**Comment by SwartzCr** [comment]
I think I've found the problem

**Comment by SwartzCr** [comment]
I think when we put cats on toys we are making a cirucular reference

**Comment by SwartzCr** [comment]
should be fixed in https://github.com/SwartzCr/nekoatsume/commit/b4c61c27062a6b5e6e1a2a5f791a5e0c2d36ac68
