### ISSUE TITLE
Gold Fish?

### ISSUE THREAD

**Issue by carystanley** [SwartzCr/nekoatsume#50]
Very fun little command-line version 😸 

Looking at your code, I don't see a way for the user to obtain gold fish

No Currency:
https://github.com/SwartzCr/nekoatsume/blob/master/lib/update.py#L112
https://github.com/SwartzCr/nekoatsume/blob/master/lib/display.py#L151

**Comment by SwartzCr** [comment]
Aww thanks for the note! It's true I haven't quite implemented all of the features.
I'd be happy to take a pull request along these lines - but otherwise am not sure when I'll have the time to get around to it.
More generally the currency is not really figured out - do you have any bright ideas for figuring out how much money cats should be leaving?
